"""initial schema

Revision ID: 10665f15cc90
Revises: 
Create Date: 2026-09-08 19:44:54.912362
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.base  # noqa: F401  custom column types (GUID, UTCDateTime)


revision = '10665f15cc90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('personas_run', sa.Integer(), nullable=False),
    sa.Column('task_completion_rate', sa.Float(), nullable=False),
    sa.Column('correct_tool_sequence_rate', sa.Float(), nullable=False),
    sa.Column('hallucinated_tool_call_rate', sa.Float(), nullable=False),
    sa.Column('avg_turns_to_resolution', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_runs'))
    )
    op.create_table('leads',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('researched_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('phone', name='uq_leads_phone')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_status', ['status'], unique=False)

    op.create_table('calls',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('lead_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider_call_sid', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.Column('final_state', sa.String(length=32), nullable=True),
    sa.Column('answered_by', sa.String(length=32), nullable=True),
    sa.Column('meeting_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('meeting_contact', sa.String(length=160), nullable=True),
    sa.Column('objection_types', sa.JSON(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('answered_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_calls_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('provider_call_sid', name='uq_calls_provider_call_sid')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_lead_id', ['lead_id'], unique=False)
        batch_op.create_index('ix_calls_outcome', ['outcome'], unique=False)

    op.create_table('cost_logs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('call_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('stt_seconds', sa.Float(), nullable=False),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=False),
    sa.Column('tts_characters', sa.Integer(), nullable=False),
    sa.Column('telephony_minutes', sa.Float(), nullable=False),
    sa.Column('stt_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('llm_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('tts_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('telephony_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_cost_logs_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_logs')),
    sa.UniqueConstraint('call_id', name='uq_cost_logs_call_id')
    )
    op.create_table('eval_results',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('run_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('call_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('persona', sa.String(length=120), nullable=False),
    sa.Column('persona_category', sa.String(length=64), nullable=True),
    sa.Column('expected_outcome', sa.String(length=32), nullable=True),
    sa.Column('actual_outcome', sa.String(length=32), nullable=True),
    sa.Column('task_completed', sa.Boolean(), nullable=False),
    sa.Column('correct_tool_sequence', sa.Boolean(), nullable=False),
    sa.Column('hallucinated_tool_call', sa.Boolean(), nullable=False),
    sa.Column('turns_to_resolution', sa.Integer(), nullable=False),
    sa.Column('final_state', sa.String(length=32), nullable=True),
    sa.Column('tool_sequence', sa.JSON(), nullable=True),
    sa.Column('failure_notes', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_eval_results_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], name=op.f('fk_eval_results_run_id_eval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_results'))
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index('ix_eval_results_run_id', ['run_id'], unique=False)

    op.create_table('transcript_turns',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('call_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('tool_called', sa.String(length=64), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('tool_valid', sa.Boolean(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('turn_index >= 0', name=op.f('ck_transcript_turns_turn_index_non_negative')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_transcript_turns_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_turns')),
    sa.UniqueConstraint('call_id', 'turn_index', name='uq_transcript_turns_call_turn')
    )
    with op.batch_alter_table('transcript_turns', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_turns_call_id', ['call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_turns', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_turns_call_id')

    op.drop_table('transcript_turns')
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_results_run_id')

    op.drop_table('eval_results')
    op.drop_table('cost_logs')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index('ix_calls_outcome')
        batch_op.drop_index('ix_calls_lead_id')

    op.drop_table('calls')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_status')

    op.drop_table('leads')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
